xgblauncher_setup_p4
alipay/ant-xgboost pull request #13
Opened 2019-08-05 13:35 UTC by sperlingxx

This is part 4 of xgblauncher setup work, which include
* Main entrance and train/predict pipelines
* Predictor
* OSSModelSource
* README

2019-08-05 15:26 UTC, yinlou commented on xgboost-launcher/README.md
> +XGBoost-Launcher is a separate python package (based on python >= 3.6), which depend on xgboost python package.
depends

2019-08-05 15:26 UTC, yinlou commented on xgboost-launcher/README.md
> +Running below codes, XGBoost-Launcher and its dependencies on will be installed.
Running the code below

2019-08-05 15:27 UTC, yinlou commented on xgboost-launcher/README.md
> +Running below codes, XGBoost-Launcher and its dependencies on will be installed.
remove "on"

2019-08-05 15:27 UTC, yinlou commented on xgboost-launcher/README.md
> +Running with united configure is a recommended way to launch xgboost-launcher, because it is easy to package for remote cluster (e.g. k8s) submission.
united -> unified

2019-08-05 15:28 UTC, yinlou commented on xgboost-launcher/README.md
> +Running with united configure is a recommended way to launch xgboost-launcher, because it is easy to package for remote cluster (e.g. k8s) submission.
add "," after "e.g."

2019-08-05 15:28 UTC, yinlou commented on xgboost-launcher/README.md
> +Here is a demo to run a stand-alone job with united configure.
standalone

2019-08-05 15:28 UTC, yinlou commented on xgboost-launcher/README.md
> +Here is a demo to run a stand-alone job with united configure.
unified

2019-08-06 00:18 UTC, yinlou commented on xgboost-launcher/launcher/main.py
> +    def build_train_d_matrix(data_source: DataSource):
Rename this function to `build_dmatrix` since it is used to load dmatrix for both training and validation?

2019-08-06 00:31 UTC, yinlou commented on xgboost-launcher/launcher/main.py
> +            skip_list=['max_depth', 'eta'])
The `skip_list` is used in `auto_train` method call to avoid checking parameters to tune. I'm not sure if you bring it outside is the right way; you can still check parameter inside `train` and `auto_train` but that's sort of doing duplicate work. Maybe we should factor out different functions for checking different groups of parameters?

2019-08-06 00:52 UTC, merlintang requested changes
overall, i am ok with this PR. but I have one big concern. 
user still do not know how to use xgb launcher. the readme of xgb launcher would be updated, and make new users to understand 1. why use xgb luancher, 2. how to use xgb launcher. step 1, step 2, step3.  3. the details to configure data source and model source would be given the rest of pr.

2019-08-06 00:52 UTC, merlintang commented on xgboost-launcher/README.md
> +##### DataSource
the data source abstraction is little hard to understand for ds.

2019-08-06 00:52 UTC, merlintang commented on xgboost-launcher/launcher/__init__.py
> +from .model_source import ModelSource, register_model_source
what is the model source meaning here ? in the readme, can you describe these concepts there ?

2019-08-06 00:52 UTC, merlintang commented on xgboost-launcher/launcher/main.py
> +    dm_builder = XGBoostDataBuilder.create(conf, ds)
the databuilder concept is too new to follow.

2019-08-06 00:52 UTC, merlintang commented on xgboost-launcher/launcher/main.py
> +        xgb_conf['params'] = automl_core.check_xgb_parameter(
why automl_core here ?

2019-08-06 01:41 UTC, sperlingxx commented on xgboost-launcher/launcher/main.py
> +            skip_list=['max_depth', 'eta'])
It's done.

2019-08-06 01:44 UTC, sperlingxx commented on xgboost-launcher/launcher/main.py
> +        xgb_conf['params'] = automl_core.check_xgb_parameter(
Because we want to check parameter explicitly before training.

2019-08-06 01:45 UTC, sperlingxx commented on xgboost-launcher/launcher/__init__.py
> +from .model_source import ModelSource, register_model_source
I will add more description and a runnable demo for data source and model source.

2019-08-06 03:32 UTC, merlintang commented
overall, i am ok with this pr, but the update for the readme is required for the next pr. 
thanks @sperlingxx

2019-08-06 03:37 UTC, merged